### ISSUE TITLE
How change View for specific container in the controller?

### ISSUE THREAD

**Issue by victorward** [roskenet/springboot-javafx-support#22]
First of all, I would like to thank for a wonderful addition to Spring.
I know that it is possible to change the View of the whole window by
`Main.showView(SomeView.class);`
But how can I change it only for a specific container in the controller?
E.g.
`@FXMLController
public class MainWindowController {
@FXML
private AnchorPane anchorPane;
}`

`public class ScreensManager {
   public void showOtherWindow() {
        Parent rootNode= (Parent) load(Other.class);
        mainWindowController.getAnchorPane().getChildren().clear();
        mainWindowController.getAnchorPane().getChildren().add(rootNode);
    }
}`

**Comment by roskenet** [comment]
Hi, thanks for your comment.
Changing components dynamically in that way doesn't fit very well with declarative FXML.
Maybe this helps you:
https://stackoverflow.com/questions/11563298/how-to-change-sub-fxml-gui-parts-at-runtime-with-button-click

I'll play around a bit with it, and try to implement an easier solution.

**Comment by roskenet** [comment]
Please clone 
https://github.com/roskenet/spring-javafx-examples
And take a look at my naive approach in part_7.
This is what you want to do, no?

**Comment by victorward** [comment]
So that's it! Thank you very much :)
