### ISSUE TITLE
Adding other spring based components

### ISSUE THREAD

**Issue by roskenet** [roskenet/springboot-javafx-support#24]
Copied from https://github.com/roskenet/spring-javafx-examples/issues/2

> This isn't an issue, but rather a question.
> I'm trying to add an accessor for a HyperSQL database to the springboot-javafx example. (Based on this example: http://www.giantflyingsaucer.com/blog/?p=2934) But, my database classes are not being found by the FXMLController class.
> 
> Can you help with an example of how to do this?
> 
> Danke!
> Thom

**Comment by roskenet** [comment]
Hi Thom,
this is not enough info for me to figure out what's going on in your app.

Please provide a complete example (preferably as a stripped down github repo), so that I can figure out if this is really an issue in the support library or how I can assist you in your configuration.

Feel free to email me directly: f.roske@roskenet.de

**Comment by pixelpshr** [comment]
Thanks for your gracious offer! I will send an email directly.

-Thom

**Comment by roskenet** [comment]
Not an issue of springboot-javafx-support.
