### ISSUE TITLE
Example for passing parameters into controller of sub-control

### ISSUE THREAD

**Issue by Ablu** [roskenet/springboot-javafx-support#25]
Hello,

I am missing an example of how I can pass values into a controller. I do not really get to see the controller when using this tool, right?

Could you maybe help me to give an idea of how to still be able to pass values into the controller from a parent controller? (Example: I have a list where I select one item and now want to display more detailed info about this specific entry in a new window).

**Comment by Ablu** [comment]
Ah. I looked into the code, and apparently the getPresenter() is the controller? I will test it.

**Comment by Ablu** [comment]
Works perfectly!

**Comment by roskenet** [comment]
Feel free to add a stripped down example of how you do it to:
https://github.com/roskenet/spring-javafx-examples

**Comment by PolkovnikMedved** [comment]
Hello,

I'm facng the same problem, so could we have a proper way to pass data when we change the view ? 

Thanks :)

**Comment by roskenet** [comment]
Hi @PolkovnikMedved 
I am not really sure if I get the problem correctly.
'Usually' (as there are a hundred possible frontend architectural concepts) the JavaFX-way is using property bindings to have your views updated 'auto-magically'.
But this is a general concept not tied the spring-support lib.
it would be perfect, if you could provide a (stripped down as necessary) example where you are stuck...

**Comment by PolkovnikMedved** [comment]
Hi @roskenet 
Well, I'm a web developer so for me it's usual if I have a table with some data (Let's say that we have a table containing countries and information about this countries) and I click on an element of a particular row (Let's say I click on a particular country) so I go to another html page with all data of this element (all the information about this country). 

I've solved this but I'm not sure that my solution is a clean solution ... 

I have a table of documents: 
```
@FXMLController
public class DocumentsController implements Initializable {

    private DocumentRepository documentRepository;
    private DocumentView documentView;

    @FXML
    private TableView<Document> documentsTableView;

    @FXML
    private TableColumn<Document, String> nameTableColumn;

    @FXML
    private TableColumn<Document, String> labelTableColumn;

    @FXML
    private TableColumn<Document, String> referenceTableColumn;

    @FXML
    private TableColumn<Document, Long> categoryTableColumn;

    @FXML
    private TableColumn<Document, Long> sensitivityTableColumn;

    @FXML
    private TableColumn<Document, String> retentionTableColumn;

    @FXML
    private TableColumn<Document, Boolean> hasAnonymisationRight;

    @FXML
    private TableColumn<Document, Boolean> hasInformationRight;

    @FXML
    private TableColumn<Document, Boolean> hasForgetRight;

    @FXML
    private TableColumn<Document, Boolean> hasRectificationRight;

    @FXML
    private TableColumn<Document, Boolean> hasPortabilityRight;

    @FXML
    private TableColumn<Document, Boolean> hasAccessRight;

    @FXML
    private TableColumn<Document, String> createdBy;

    @FXML
    private TableColumn<Document, String> createdAt;

    private void populateTable() {
        nameTableColumn.setCellValueFactory(new PropertyValueFactory<>("name"));
        nameTableColumn.getStyleClass().add("disabledCell");

        labelTableColumn.setCellValueFactory(param -> new SimpleStringProperty(param.getValue().getLabel().getFrenchLabel()));
        labelTableColumn.setEditable(true);
        labelTableColumn.setCellFactory(TextFieldTableCell.forTableColumn());

        documentsTableView.setOnMouseClicked(event -> {
                if (!(event.getTarget() instanceof TableColumnHeader) && event.getClickCount() == 2 && documentsTableView.getSelectionModel().getSelectedCells().get(0).getColumn() == 0) {
                    DocumentController documentController = (DocumentController) documentView.getPresenter();
                    documentController.initData(documentsTableView.getSelectionModel().getSelectedItem().getName());
                    Application.showView(DocumentView.class);
                }
        });

        documentsTableView.setEditable(true);
        ObservableList<Document> dataObservableList = FXCollections.observableList(this.documentRepository.findAll());
        this.documentsTableView.itemsProperty().setValue(dataObservableList);

```

So as you can see I have a table of documents and when I double-click on a partcicular document identifier I get the DocumentController by '(DocumentController) documentView.getPresenter();' and then I call the `initData()` method with the document identifier on which I've clicked. 

Now, I can see all the elements of a particular ´Document´.
