### ISSUE TITLE
Application Context when creating a new Stage

### ISSUE THREAD

**Issue by vrn-dev** [roskenet/springboot-javafx-support#26]
Great library roskent! Excellent work.

I have an issue that if I create another stage away from the main stage, like a modal, then the modal is not aware of the application context.

I changed the example part-6-2 to illustrate:

`@FXMLController
public class ViewController {
    
    public void showFirstView(Event event) {
        Main.showView(FirstView.class);
        System.out.println("clicked");
    }

    public void showSecondView(Event event) throws IOException {
        //Main.showView(SecondView.class);
        Parent root = FXMLLoader.load(ViewController.class.getResource("second.fxml"));
        Scene scene = new Scene(root);
        Stage stage = new Stage();
        stage.setScene(scene);
        stage.show();
    }
}`

In this case, when I click First View button in then new Second View Stage, nothing happens.

Any advise as to how to go about solving this?

**Comment by roskenet** [comment]
Thanks for your comment.
Will check for an easy to use solution to show modals registered in the appCtx in a consistent way.
Stay tuned...

**Comment by roskenet** [comment]
But - this won't create a modal window. 
Maybe check
https://examples.javacodegeeks.com/desktop-java/javafx/dialog-javafx/javafx-dialog-example/

**Comment by vrn-dev** [comment]
This is not extending the appCtx to the SecondView, it is loading the view with context but not injecting into SecondView controller

**Comment by roskenet** [comment]
Yes, sure. ViewController is a Spring Bean which are by default singletons.
I am not 100% sure if I understand, what you want to achieve. Perhaps you should create a different controller for your SecondView (to keep the example simple, I used a single ctrl. for both views).

I tried something. Please check part_8 in the examples as soon as springboot-javafx-support 1.3.30 is available in maven central.

Is it something like this, that you need?

Feel free to contact me via p.m. f.roske@roskenet.de

**Comment by victorward** [comment]
Hi, it works fine for me, and could you tell me how get Stage of this Controller? I need Stage for handling my custom Close button.

**Comment by vrn-dev** [comment]
Hi, perfectly done, with a new static method for new Stages! Will use this in my dev and let you know if any problems crop up
