### ISSUE TITLE
Not populating @FXML fields on initialize method

### ISSUE THREAD

**Issue by DiasNetoJ** [roskenet/springboot-javafx-support#27]
Initializable controllers is not populating @FXML annotated fields, see example:

```
@FXMLController
public class Helloworld implements Initializable  {
    @FXML
    private Label helloLabel;

    @FXML
    private TextField nameField;

    @FXML
    private void setHelloText(final Event event) {
        final String textToBeShown = nameField.getText();
        helloLabel.setText(textToBeShown);
    }

    @FXML
    @Override
    public void initialize(URL location, ResourceBundle resources) {
        nameField.setText("Testing..."); //NPE, cause nameField is null
    }
}

```

**Comment by roskenet** [comment]
Not reproduceable.
Please check if you have set the correct IDs in your FXML.

**Comment by DiasNetoJ** [comment]
The IDs is correct.
I noticed that in initialize method the Spring beans are populated but @FXML fields are not,
but when I trigger an event by a button the Spring beans are not populated but @FXML fields are.

In my tests, there are two instance of my controller class.

**Comment by roskenet** [comment]
Could you please provide a complete (stripped down) example (preferably in a repo)?
I added your snippet from above to part_2 of the examples and JavaFX "autowired" the FXML correctly.

[And by the way: implementing Initializable is not recommended anymore (see docu of Initializable).]

**Comment by DiasNetoJ** [comment]
The root cause is AOP, and it is simple to reproduce:

Add the following maven dependencies:
```
    <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aop</artifactId>
            <version>4.3.10.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjweaver</artifactId>
            <version>1.8.10</version>
        </dependency>

```
Then create a Logging class in example package:

```
package example;

import org.aspectj.lang.annotation.AfterThrowing;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Pointcut;
import org.springframework.stereotype.Component;

/**
 * Created by Dias on 18/08/2017.
 */
@Aspect
@Component
public class Logging {
    @Pointcut("execution(* example..*.*(..))")
    public void allMethods() {
    }

    @AfterThrowing(pointcut = "allMethods()", throwing = "e")
    public void AfterThrowingAdvice(Throwable e){
        System.out.println("There has been an exception: " + e.toString());
    }
}
```

Now when I hit the button, my actionService variable is null and the @FXML fields are populated.

**Comment by roskenet** [comment]
So, it's the other way round, than you initially posted?

It would really be more helpful to provide us with a complete example.
Thanks.

**Comment by DiasNetoJ** [comment]
> So, it's the other way round, than you initially posted?

I would not say it that way... I just grabbed the example available here: https://www.felixroske.de/page/programmierung/index.html

and put into my **existing project that uses AOP**, i.e., I just realize that AOP was the problem, later...

> It would really be more helpful to provide us with a complete example.

Sure: https://github.com/DiasNetoJ/spring-javafx-examples/tree/master/part_2

> [And by the way: implementing Initializable is not recommended anymore (see docu of Initializable).]

I almost forgot to answer you about it. Really thank you! I will see the docs.

**Comment by krystiankaluzny** [comment]
Hi, this thread catch my attention so I made some spring code investigation. And results are as follows.
When you use aspects, Spring create proxies (obviously). But there are 2 types of proxy
JdkDynamicAopProxy and ObjenesisCglibAopProxy. 
The first one is using as proxy to interface. So in this case, "helloworld" bean isn't instance of Helloworld class. But it is instance of some proxy class that implements Initializable interface and have delegate object to Helloworld class. 
FXMLLoader tried to inject fields into proxy class instead of real Helloworld class that's why helloLabel and nameField were NULL.

The second AopProxy implementation create subclass but doesn't call base class constructor so all fields initially are NULL. It also have delegate object to Helloworld class.
In this case FXMLLoader can inject fields with @FXML annotation.
But there is problem with autowiring, cause Spring create original Helloworld object and inject its dependency then create ObjenesisCglibAopProxy and set first one as delegate.

If your controller doesn't implement any Interfaces then you can set all method as private and create public getters to autowiring fields.

```
@FXMLController
public class Helloworld {
    @FXML
    private Label helloLabel;
    @Autowired
    private ActionService actionService;

    @FXML
    private void setHelloText(final Event event) {
            actionService.doSomething() //NPE because this is Helloworld$EnhancerByCGLIB class
             getActionService().doSomething() //OK because Helloworld$EnhancerByCGLIB#getActionService call public Helloworld#getActionService method
    }

   public ActionService getActionService() {
            return actionService;
   }
}
```

[https://stackoverflow.com/questions/34563058/spring-aop-cglib-proxys-field-is-null](spring-aop-cglib-proxys-field-is-null)

**Comment by roskenet** [comment]
@krystiankaluzny Great post. Thanks a lot for that!

**Comment by DiasNetoJ** [comment]
@krystiankaluzny, awesome, it works! Thank you.
Now suppose I need implement some initialize method to my controller, is there any workaround to deal with null @FXML fields?
```
@FXMLController
public class HelloworldController {

    @FXML
    private Label helloLabel;
  
    @FXML
    private TextField nameField;
    
    // Be aware: This is a Spring bean. So we can do the following:
    @Autowired
    private AwesomeActionService actionService;

    public AwesomeActionService getActionService() {
        return actionService;
    }

    public void initialize() {
        System.out.println(helloLabel.getText());
    }

    @FXML
    private void setHelloText(final Event event) {
       final String textToBeShown = getActionService().processName(nameField.getText());
       helloLabel.setText(textToBeShown); 
    }
}
```

**Comment by roskenet** [comment]
Solved and not directly related to springboot-java-support.

**Comment by krystiankaluzny** [comment]
@DiasNetoJ, A code is worth a thousand words. Look at 
https://github.com/krystiankaluzny/spring-javafx-examples/blob/aop/part_2/src/main/java/example/HelloworldController.java

**Comment by DiasNetoJ** [comment]
@krystiankaluzny awesome, it works! Really thank you.

**Comment by yangon-jdc** [comment]
Thank you @krystiankaluzny 
I have the same problem and solved now.
Your explanation is so great.
