### ISSUE TITLE
Question about package configuration

### ISSUE THREAD

**Issue by krystofurr** [roskenet/springboot-javafx-support#28]
Hi there,

 I started using your library the other day and read through a tutorial here:

 https://www.felixroske.de/page/programmierung/index.html

 Had a few issues that seem to be related to file location.  The tutorial uses a single package ( example ) for all config, view and controller classes.  As well, the resources folder matches the package name.  It seems that if I deviate from the package structure at all, the view class cannot locate the associated .fxml file at all.  If you have your view class in one package ( say com.myfxapp.config ) and your controller in a different package ( say com.myfxapp.controller ) and the .fxml file in src/main/resources/fxml, how does one configure the path structure ?  Or are you limited to needing the same package / folder for all files ?  On the annotation I did see that you can set a relative path which was good.  Can you do this for the controller as well ?  Thanks!

Regards,
Chris

**Comment by roskenet** [comment]
Hi @krystofurr 
As you mentioned, the library expects the fxml file in the same package (directory structure) as the view wrapper class. You can override this default by providing a value to the  @FXMLView annotation:

Given in a standard maven project your fxml file is in src/main/resources/mypath/myview.fxml you add:
@FXMLView("/mypath/myview.fxml")

I try to make this more clear in the docu. Thanks.

**Comment by krystofurr** [comment]
Understood!  Thanks very much.
