### ISSUE TITLE
Add /fxml/ as default resource path

### ISSUE THREAD

**Issue by roskenet** [roskenet/springboot-javafx-support#3]
For backwards compatibility and easier usage of @FXMLView annotation add /fxml/ as a possible fxml location.

**Comment by ajesh123** [comment]
Its good. Better to use PathMatchingResourcePatternResolver to identify *.fxml files from resource folder and register as FXMLView with getConventionalName.
http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/core/io/support/PathMatchingResourcePatternResolver.html

**Comment by roskenet** [comment]
Closed for now due to minor importance.
