### ISSUE TITLE
Two stage in the same application.

### ISSUE THREAD

**Issue by earandap** [roskenet/springboot-javafx-support#31]
Is it possible to handle two stage in the application? Basically, what I am trying to do is display two windows after the startup of the app. 
Sorry, I am a newbie with JavaFX.
Thanks in advance.

**Comment by roskenet** [comment]
Hi!
The docu is incomplete here... 
You find an example in part_8 of
https://github.com/roskenet/spring-javafx-examples

If you have any questions please contact me: f.roske@roskenet.de

**Comment by roskenet** [comment]
No issue or missing feature.
