### ISSUE TITLE
Replace autowired beans in unit tests 

### ISSUE THREAD

**Issue by deen13** [roskenet/springboot-javafx-support#33]
I have not found a way to replace the @Autwired Beans by fakes or similar in test cases. Can you please provide a example for this? 

My attempt: 

```
@RunWith(SpringRunner.class)
@SpringBootTest
public class NewsViewTest extends GuiTest {

	@MockBean private FakeNewsService fakeService;

	@PostConstruct
	public void init() throws Exception {
		initMocks(this);
		init(NewsView.class);
	}

	@Test
	public void test() {
	}

}
```

```
public interface NewsService {

	public ObservableList<Article> getLatestArticle() throws Exception;
	
}
```

```
@FXMLController
public class NewsController {

	@FXML private ListView<Article> news;
	@Autowired private NewsService service;

	private ListProperty<Article> binding = new SimpleListProperty<>();

	@FXML
	void initialize() throws Exception {
		assert news != null : "fx:id=\"news\" was not injected: check your FXML file 'helloworld.fxml'.";
		assert service != null : "No rest news service was injected";

		binding.set(service.getLatestArticle());
		news.itemsProperty().bind(binding);

		ItemSelectedListener listener = new ItemSelectedListener(news);
		news.getSelectionModel().selectedItemProperty().addListener(listener);
	}

}
```

**Comment by deen13** [comment]
A more detailed example can be found [here](https://github.com/deen13/talks/tree/talk/dependency_injection/dependency_injection/sample)

**Comment by deen13** [comment]
Any udpates here?

**Comment by roskenet** [comment]
Sorry... Again on it. ;-)

**Comment by krystiankaluzny** [comment]
I found two promising approaches to this problem, but I haven't tried to implement
1. using "test" @Profile http://www.baeldung.com/injecting-mocks-in-spring
2. using @TestConfiguration http://www.baeldung.com/spring-boot-testing

**Comment by roskenet** [comment]
Since this is not an issue related to the library itself, please check also
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html
especially 41.3.4 Mocking and spying beans
i close this here.

**Comment by deen13** [comment]
It wasn't as easy as it sounds in your'e reply but i got it. The view and controller needs to be provided manually as well. There is also a bug in the JVM, which crashes the VM under Intel HD graphics cards.

Everyone else who is struggling around with mocking dependencies, can take a look at [this](https://github.com/deen13/javafx-spring-testing)

**Comment by roskenet** [comment]
@deen13 Thanks a lot.
