### ISSUE TITLE
Create a branch for spring boot 1.5

### ISSUE THREAD

**Issue by ouaibsky** [roskenet/springboot-javafx-support#35]
Hi
Should it be possible to add a branch for patching version compatible with boot 1.5 ?
Thx
Christophe

**Comment by roskenet** [comment]
Salut!
Haven't tried out 1.5 yet. Will do so as soon as possible.

**Comment by thomasdarimont** [comment]
Version 1.4.1 works fine with Spring Boot 1.5.8.RELEASE, just built a [small demo app](https://github.com/thomasdarimont/spring-labs/tree/master/springboot-javafx-support-jpa-demo).

**Comment by roskenet** [comment]
Added development branch springboot-1.5 for compatibility to Boot 1.x
Master is for Spring Boot 2.
I think it is a good idea to upgrade applications to springboot 2 as soon as it is FINAL.

Will close this issue for now.
