### ISSUE TITLE
How do you make exe executable files?

### ISSUE THREAD

**Issue by koy-tome** [roskenet/springboot-javafx-support#42]
I need to SpringBoot-JavaFx the project into a exe executable file, but in the use of the exe4j package can run. What is the solution?
**Error is as follows:**
**Caused by: java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.**

**Comment by koy-tome** [comment]
I solved the problem:
1. use spring-boot-maven-plugin when packing.
2. entrance selection JarLaunch.

**Comment by roskenet** [comment]
Thanks a lot for posting your solution here!
