### ISSUE TITLE
Cannot get Spring context outside a Component

### ISSUE THREAD

**Issue by Blackdread** [roskenet/springboot-javafx-support#43]
Hi,

How can we get the Spring context outside a \@Component?
So far it seems that we cannot as AbstractJavaFxApplicationSupport does not provide any access to it.

Eventually we could define a Component that get it by constructor autowired then init a static variable and only then some Util classes (that we do not want to transform to Component) could poll on it until it is not null anymore.

Am I right?

EDIT: I have modified the util class to become a component but still interested to know what you would recommend.

**Comment by roskenet** [comment]
I am not sure if I get your question correctly.
This seems to be more a question about the Spring Framework, am I right?
What do you mean by "getting the context" outside a component?

**Comment by Blackdread** [comment]
I had a Util class that was not supposed to become a \@Component so I wanted to be able to get Spring context from "AbstractJavaFxApplicationSupport" class via overriding a public method to allow to get "ConfigurableApplicationContext" that is inside "AbstractJavaFxApplicationSupport" but there was no way to do.

As a result, I modified my code of the Util class to become a \@Component and I was able to do what you mentioned which is the proper way to do in Spring.

I think you can mark this issue as solved because to transform to \@Component is the best approach.

**Comment by roskenet** [comment]
O.k. Thanks.
