### ISSUE TITLE
Duplicate Code in Tag v1.4.4

### ISSUE THREAD

**Issue by fbouchedid** [roskenet/springboot-javafx-support#47]
AbstractJavaFxApplicationSupport has duplicate lines of code that is causing the beforeShowingSplash to be called twice. I have created a fork and made the modifications. The only issue is that I am not able to create a pull request since there are two paths the 1.4.X and 2.0.X and master is currently on 2.0.X. 

Here is a link to the commit on my fork:
https://github.com/fbouchedid/springboot-javafx-support/commit/2f2d361d5cce26c2af3fe3ec766534182561b30a
and I also fixed tabbing in a later commit:
https://github.com/fbouchedid/springboot-javafx-support/commit/89e2732c265543268629c0d087f392b20f629f49

Can you create a v1.4.5 release and merge my branch:
https://github.com/fbouchedid/springboot-javafx-support/tree/bug/remove-duplicate-code

Let me know if there is anything else you need from my end. Thanks!

**Comment by roskenet** [comment]
Thanks a lot!
Will check over the weekend.

**Comment by roskenet** [comment]
Merged in v1.4.5

**Comment by fbouchedid** [comment]
This is fixed in 1.4.5. I have verified it by downloading it from maven central.

**Comment by roskenet** [comment]
And now in master too.
Deployed with 2.1.5.
Thanks for your contribution!
