### ISSUE TITLE
callback event

### ISSUE THREAD

**Issue by linxu** [roskenet/springboot-javafx-support#51]
Whether there is a callback event after the view is displayed, such as data initialization。

**Comment by roskenet** [comment]
Hi @linxu 
What exactly would be your use case? Initialization should be done by your controller using:
https://docs.oracle.com/javase/8/javafx/api/javafx/fxml/Initializable.html
Please note the NOTE (simply add a method initialize(URL location, ResourceBundle resources))
Or maybe this helps you:
https://docs.oracle.com/javase/8/javafx/api/javafx/stage/WindowEvent.html

Is this what you want to do?

**Comment by linxu** [comment]
Tks @roskenet 
Initializable is what i need.

**Comment by roskenet** [comment]
Cool, then I close this.
