### ISSUE TITLE
hideView

### ISSUE THREAD

**Issue by co5dt** [roskenet/springboot-javafx-support#56]
There's the convenience method 

`public static void showView(Class<? extends AbstractFxmlView> window, Modality mode)`

Shouldn't there also be one to hide or close it?

**Comment by octaviospain** [comment]
Closing #59, now that there will be methods for showing the view in different views, I added the convenience method 
```java
public void hide() {
    if (stage != null)
        stage.hide();
}
```

**Comment by yuleefuck** [comment]
So has the problem been solved?
