### ISSUE TITLE
Move the showView method to AbstractFxmlView

### ISSUE THREAD

**Issue by octaviospain** [roskenet/springboot-javafx-support#58]
The responsibility of an `AbstractFxmlView` to be shown should recall on its own, and not on `AbstractJavaFxApplicationSupport` via a static call.

To show a view, now you have to do it this way
```java
Main.showView(FirstView.class);
```

* This makes code hardly testable.
* This gives the control of showing a class to the `Main` class (that is nothing special, just the entry point of the application), but an `AbstractFxmlView` should have the ability to be requested to be shown, and how.

The solution should provide `showView` methods to `AbstractFxmlView` so that:
* There are separation of concerns
* Code is testable since is easier to mock an instance of a class rather than an static method
* There are methods that provides ways to show a view, I. e. under which `Window`, with which `Modality`, and if the `Window` should be shown as `show` or `showAndWait`

**Comment by roskenet** [comment]
I totally agree!
Looking forward to a pull request...
Thanks so far!

**Comment by octaviospain** [comment]
I already raised the Pull Request, but it decreases the code coverage.
I will add tests soon and push the changes, in the meantime any reviews are appreciated.
