### ISSUE TITLE
Does not display the icon

### ISSUE THREAD

**Issue by TioCoding** [roskenet/springboot-javafx-support#7]
Hello, I'm exploring the framework and I think it's very good but there's something I can not solve that has to do with SplashScreen. When defining the application icon in the application.yml, when I run it without the SplashScreen (overwriting the visible method to false), the application icon works, but when I run it with the SplashScreen (overwriting the visible method to true or By default) does not display the icon that you configure in the application.yml, it shows the default of Javafx, maybe something I am doing wrong, please I would like your help. Thank you so much :smiley: 

![imgquey2](https://cloud.githubusercontent.com/assets/22163898/25065791/474e18bc-21db-11e7-896a-2331f1a38089.png)

**Comment by roskenet** [comment]
Yes. I understand.
The problem with this is, that while showing the SplashScreen there is no Spring application context yet and the application.yaml is not available. That means that we would need some other means to configure the application icon while loading.
But it should show your configured one, when the app has loaded completely, right?
I try to find a solution for that.

**Comment by TioCoding** [comment]
Thanks for the quick response, when I run with the splash screen, sometimes it shows the icon and sometimes does not show it (depends on how long it takes to open the main window), but when I run it without splash screen, if it takes the application.yml configuration (it works perfectly). Maybe there is some way to configure it before running the application, an overwriting method in the SplashScreen class.

**Comment by roskenet** [comment]
I see... Seems to be related to this on Ubuntu (KDE, Win, Mac are fine):
http://stackoverflow.com/questions/38172689/javafx-app-icon-fails-to-show-9-10-times
(The answer in this thread is not really correct...)
I will address this.

**Comment by roskenet** [comment]
Closed due to a bug in GTK.
